name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: 1. Automatic Build
      run: dotnet build --no-restore --configuration Release

    - name: 2. Run Unit Tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: 3. Static Code Analysis
      run: dotnet format --verify-no-changes
      continue-on-error: true 

    - name: 4. Publish
      run: dotnet publish MPDA_Proiect2/MPDA_Proiect2.csproj -c Release -o ./deployment_drop

    - name: 5. Deploy 
      uses: actions/upload-artifact@v4
      with:
        name: WebApp-Release
        path: ./deployment_drop
